<a href="https://colab.research.google.com/github/osmyildiz/data_analysis/blob/master/Assignment_1_Student.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!


#### 1. Import NumPy Library

In [4]:
import numpy as np

#### 2. Create an array from my_list=[5,10,15,20,25]

In [3]:
a = np.arange(5,30,5)
a

array([ 5, 10, 15, 20, 25])

#### 3. Generate an array 5x5 zeros 

In [6]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### 4. Generate an array 4x4 ones assign data type int

In [8]:
np.ones((4,4),int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

#### 5. Make all the values of the array above 7

In [9]:
np.ones((4,4),int)*7

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 6. Create same array above with full method

In [10]:
np.full((4,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 7. Create an array of even integers from 2 to 16 

In [11]:
np.arange(2,18,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16])

#### 8. Create a 5x5 matrix with values between 0 to 25

In [5]:
np.random.randint(25, size=(5, 5))

array([[21, 24, 19, 23, 18],
       [ 2,  9, 24,  6, 16],
       [19, 22, 24, 19, 15],
       [ 7, 15, 15, 12, 14],
       [24,  2, 14,  6, 16]])

#### 9. Create a 5x5 matrix with values between 0 to 25 using linspace

In [7]:
np.linspace(0,24,25).reshape(5,5)

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

#### 10. Create 5 random number with numpy

In [17]:
np.random.rand(5)

array([0.96419727, 0.82712153, 0.26621204, 0.36709506, 0.55145831])

#### 11. Create random normal distributed 5x5 array

In [19]:
np.random.randn(5,5)

array([[-0.27758646,  1.02181451,  1.75870106, -1.33368698,  0.64830816],
       [-0.92833991, -1.84161355,  0.39768732, -2.20140278,  1.98313461],
       [ 1.15031035, -0.27333392,  0.56678066,  0.80876975,  0.18889738],
       [-1.18106816, -1.58366715,  0.79505636, -1.64267522, -0.44820439],
       [ 0.12066556,  0.55191035,  0.53063524, -0.6572778 ,  0.99914564]])

#### 12. Create 3x4 shaped array with random int numbers between 20 and 50 with numpy

In [21]:
np.random.randint(20,50,size=(3,4))

array([[21, 28, 30, 22],
       [36, 29, 30, 46],
       [30, 43, 26, 21]])

#### 13. Reshape the array below with shape 6x8

In [9]:
ranarr = np.array([49,  1,  8, 15, 54,  7, 18, 51, 25,  7, 54,  1, 55, 12, 16, 44,
         3, 59, 59, 31,  1, 40,  6, 12, 41,  6, 13, 47, 11, 40, 33,  9,
        44, 23, 24, 18, 11,  2, 21, 57, 42, 23,  4, 15, 18, 33, 16, 17])
ranarr.reshape(6,8)


array([[49,  1,  8, 15, 54,  7, 18, 51],
       [25,  7, 54,  1, 55, 12, 16, 44],
       [ 3, 59, 59, 31,  1, 40,  6, 12],
       [41,  6, 13, 47, 11, 40, 33,  9],
       [44, 23, 24, 18, 11,  2, 21, 57],
       [42, 23,  4, 15, 18, 33, 16, 17]])

In [10]:
ranarr.reshape(1,48)

array([[49,  1,  8, 15, 54,  7, 18, 51, 25,  7, 54,  1, 55, 12, 16, 44,
         3, 59, 59, 31,  1, 40,  6, 12, 41,  6, 13, 47, 11, 40, 33,  9,
        44, 23, 24, 18, 11,  2, 21, 57, 42, 23,  4, 15, 18, 33, 16, 17]])

In [11]:
ranarr.reshape(6,8)

array([[49,  1,  8, 15, 54,  7, 18, 51],
       [25,  7, 54,  1, 55, 12, 16, 44],
       [ 3, 59, 59, 31,  1, 40,  6, 12],
       [41,  6, 13, 47, 11, 40, 33,  9],
       [44, 23, 24, 18, 11,  2, 21, 57],
       [42, 23,  4, 15, 18, 33, 16, 17]])

In [30]:
#reshape with -1
ranarr.reshape(4,-1)


array([[49,  1,  8, 15, 54,  7, 18, 51, 25,  7, 54,  1],
       [55, 12, 16, 44,  3, 59, 59, 31,  1, 40,  6, 12],
       [41,  6, 13, 47, 11, 40, 33,  9, 44, 23, 24, 18],
       [11,  2, 21, 57, 42, 23,  4, 15, 18, 33, 16, 17]])

## Numpy Indexing and Selection


In [13]:
#Create array below
mat= np.array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### 14. Write code that reproduces the output shown below.<br>

In [14]:
mat[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

#### 15. Get the first column of the array.

In [15]:
mat[:,0]

array([ 1,  5,  9, 13])

#### 16. Get the values in 2nd row for every 2 step.

In [34]:
mat[1,::2]

array([5, 7])

#### 17.Assign 77 to every cell in 3rd column.

In [57]:
mat[:,2]=77

In [58]:

mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

#### 18. Take 2nd row 1st column, 4th row 2nd column.

In [59]:
mat[[1,3],[0,1]]

array([ 5, 14])

#### 19. Take between 2nd and last row with step 2 and between 1 and last column with step 2.

In [50]:
mat[1::2,0::2]


array([[ 5, 77],
       [13, 77]])

## NumPy Operations

#### 20. Get the sum of values smaller than 10 and values bigger than 12 from array above 

In [16]:
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [19]:
mat[(mat>12)]

array([13, 14, 15, 16])

In [20]:
mat[(mat<10)]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

array([78, 79, 81, 18, 20, 85, 25])

#### 21. Get the standard deviation of the result above

In [70]:
x = np.array([77, 77, 77, 13, 14, 77, 16])
x.std()

31.022703996674856

In [71]:
y = np.array([78, 79, 81, 18, 20, 85, 25])
y.std()

29.700546274093877

#### 22. Get the sum of second column from array above

In [73]:
mat[:,1].sum()


32

#### 23. Get the median,mean and std of 3rd row from array above

In [21]:
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [22]:
mat[2]

array([ 9, 10, 11, 12])

In [24]:
#median
mat = np.array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])
mat
np.median(mat[2])



10.5

In [25]:
#mean
np.mean(mat[2])


10.5

In [26]:
#std
np.std(mat[2])

1.118033988749895

# Pandas Section

In [31]:
import pandas as pd

**Read Salaries.csv take a look at first 5 rows, df info and df statistical measurements**

In [33]:
sal=pd.read_csv('/content/sample_data/Salaries.csv')

FileNotFoundError: ignored

In [122]:
sal.head()

Id       EmployeeName  ...         Agency Status
0   1     NATHANIEL FORD  ...  San Francisco    NaN
1   2       GARY JIMENEZ  ...  San Francisco    NaN
2   3     ALBERT PARDINI  ...  San Francisco    NaN
3   4  CHRISTOPHER CHONG  ...  San Francisco    NaN
4   5    PATRICK GARDNER  ...  San Francisco    NaN

[5 rows x 13 columns]

In [123]:
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148049 non-null  object 
 4   OvertimePay       148654 non-null  object 
 5   OtherPay          148654 non-null  object 
 6   Benefits          112495 non-null  object 
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            38119 non-null   object 
dtypes: float64(3), int64(2), object(8)
memory usage: 14.7+ MB


In [124]:
sal.describe()

Id       TotalPay  TotalPayBenefits           Year  Notes
count  148654.000000  148654.000000     148654.000000  148654.000000    0.0
mean    74327.500000   74768.321972      93692.554811    2012.522643    NaN
std     42912.857795   50517.005274      62793.533483       1.117538    NaN
min         1.000000    -618.130000       -618.130000    2011.000000    NaN
25%     37164.250000   36168.995000      44065.650000    2012.000000    NaN
50%     74327.500000   71426.610000      92404.090000    2013.000000    NaN
75%    111490.750000  105839.135000     132876.450000    2014.000000    NaN
max    148654.000000  567595.430000     567595.430000    2014.000000    NaN

**How many different year value are there**

In [125]:
sal['Year'].value_counts()

2014    38123
2013    37606
2012    36766
2011    36159
Name: Year, dtype: int64

**Print out max and avg Totalpay**

In [126]:
#max
sal['TotalPay'].max()

567595.43

In [127]:
#avg
sal['TotalPay'].mean()

74768.321971703

**How many records are there which have TotalPay bigger than avg TotalPay**

In [30]:
sal.TotalPay[sal.TotalPay>sal.TotalPay.mean()].count()

NameError: ignored

**How much does ALBERT PARDINI make (including benefits)?**

In [144]:
sal[sal["EmployeeName"]=="ALBERT PARDINI"]["TotalPayBenefits"]

2    335279.91
Name: TotalPayBenefits, dtype: float64

**Who is lowest paid person**

In [145]:
sal[sal['TotalPayBenefits']  == sal['TotalPayBenefits'].min()]['EmployeeName']

148653    Joe Lopez
Name: EmployeeName, dtype: object

**What are the unique Jobs in dataset?**

In [146]:
sal["JobTitle"].unique()

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

In [147]:
sal["JobTitle"].unique()

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

**List 3 least common Jobs**

COURT COMPUTER FACILITIES COORDINATOR             1
AUTOMOTIVE BODY AND FENDER WORKER SUPERVISOR I    1
VICTIM & WITNESS TECHNICIAN                       1
Name: JobTitle, dtype: int64

In [151]:
sal["JobTitle"].value_counts(ascending=False).sort_values()[0:3]

SENIOR TRANSIT TRAFFIC CHECKER                1
MAYORAL STAFF II                              1
ASSISTANT DIRECTOR OF CLINICAL SERVICES II    1
Name: JobTitle, dtype: int64

**How many people earned more than avg in 2012**

In [176]:
sal[ (sal.TotalPayBenefits>sal.TotalPayBenefits.mean()) & (sal.Year==2012) ].count()

20366

**How many people have the word Manager in their job title?**

In [181]:
#use apply function here
sum(sal['JobTitle'].apply(lambda x:"manager" in x.lower()))


4110

**Take Id,EmployeeName,JobTitle,TotalPay and TotalPayBenefits columns with iloc and assign it as sal_new dataframe**

In [182]:
sal.head()

Id       EmployeeName  ...         Agency Status
0   1     NATHANIEL FORD  ...  San Francisco    NaN
1   2       GARY JIMENEZ  ...  San Francisco    NaN
2   3     ALBERT PARDINI  ...  San Francisco    NaN
3   4  CHRISTOPHER CHONG  ...  San Francisco    NaN
4   5    PATRICK GARDNER  ...  San Francisco    NaN

[5 rows x 13 columns]

In [186]:
sal_new=sal.iloc[:,[0,1,2,7,8]]
sal_new

Id       EmployeeName  ...   TotalPay  TotalPayBenefits
0            1     NATHANIEL FORD  ...  567595.43         567595.43
1            2       GARY JIMENEZ  ...  538909.28         538909.28
2            3     ALBERT PARDINI  ...  335279.91         335279.91
3            4  CHRISTOPHER CHONG  ...  332343.61         332343.61
4            5    PATRICK GARDNER  ...  326373.19         326373.19
...        ...                ...  ...        ...               ...
148649  148650      Roy I Tillery  ...       0.00              0.00
148650  148651       Not provided  ...       0.00              0.00
148651  148652       Not provided  ...       0.00              0.00
148652  148653       Not provided  ...       0.00              0.00
148653  148654          Joe Lopez  ...    -618.13           -618.13

[148654 rows x 5 columns]

**Take columns betweeen EmployeeName and TotalPayBenefits with loc and assign it o sal_new df**
 

In [192]:
sal_new=sal_new.loc[:,"EmployeeName":"TotalPayBenefits"]
sal_new

EmployeeName  ... TotalPayBenefits
0          NATHANIEL FORD  ...        567595.43
1            GARY JIMENEZ  ...        538909.28
2          ALBERT PARDINI  ...        335279.91
3       CHRISTOPHER CHONG  ...        332343.61
4         PATRICK GARDNER  ...        326373.19
...                   ...  ...              ...
148649      Roy I Tillery  ...             0.00
148650       Not provided  ...             0.00
148651       Not provided  ...             0.00
148652       Not provided  ...             0.00
148653          Joe Lopez  ...          -618.13

[148654 rows x 4 columns]

**Print out the names of the employees who earn more than min, but less than avg**

In [200]:
sal_new[(sal_new["TotalPayBenefits"]>sal_new["TotalPayBenefits"].min()) & (sal_new["TotalPayBenefits"]<sal_new["TotalPayBenefits"].mean()) ]["EmployeeName"]

10806            KWE LEE
10807     MIGUEL CARO JR
10808      JOANNE MORRIS
10809      LAYLA WELBORN
10810            LE BANH
               ...      
148648       Leon Walker
148649     Roy I Tillery
148650      Not provided
148651      Not provided
148652      Not provided
Name: EmployeeName, Length: 75649, dtype: object